# Compilation installation path.
# Supports environment variable expansions using ${VARIBLE}
install_path: ${HOME}/.config

# The file suffix used for override files
override_suffix: override

# The file suffix to use for installation files
install_suffix: install

groups:
  - base
  - common/platform-arch
  - common/dev
  - common/de-i3
#  - common/platform-debian
#  - common/de-xfce
#  - machines/xps
#  - machines/remote
#  - machines/server

# Groups to compile for all profiles
base_groups: [base]
# Configuration profiles. Each configuration profile should map to a list of
# source paths to compile. Order defines the cascade order.
profiles:
  xps-cli:
    - common/platform-arch
    - common/dev
  xps:
    - common/platform-arch
    - common/de-i3
    - common/dev
#    - machines/xps
#   remote:
#    - common/platform-debian
#    - common/development
#    - machines/remote
