# Compilation installation path.
# Supports environment variable expansions using ${VARIBLE}
install_path: ${HOME}/.config

# The file suffix used for override files
override_suffix: override

# The file suffix to use for installation files
install_suffix: install

groups:
  - base
  - distro/arch/cli
  - distro/arch/gui
  - distro/arch/i3wm
  - distro/debian
  - machines/xps
#  - machines/remote
#  - machines/server

# Groups to compile for all profiles
base_groups: [base]
# Configuration profiles. Each configuration profile should map to a list of
# source paths to compile. Order defines the cascade order.
profiles:
  arch:
    - distro/arch/cli
  arch-i3:
    - distro/arch/cli
    - distro/arch/gui
    - distro/arch/i3wm
  xps:
    - distro/arch/cli
    - distro/arch/gui
    - distro/arch/i3wm
    - machines/xps
#   remote:
#    - common/platform-debian
#    - common/development
#    - machines/remote
