# Compilation installation path.
# Supports environment variable expansions using ${VARIBLE}
install_path: ${HOME}/.config

# The file suffix used for override files
override_suffix: override

# The file suffix to use for installation files
install_suffix: install

groups:
  - base
  - machines/xps
  - machines/remote
  - machines/server
  - common/platform-arch
  - common/platform-debian
  - common/development
  - common/i3
  - common/xfce

# Groups to compile for all profiles
base_groups: [ base ]

# Configuration profiles. Each configuration profile should map to a list of
# source paths to compile. Order defines the cascade order.
profiles:
  personal:
    - common/platform-arch
    - common/i3
    - common/development
    - machines/xps
  remote:
    - common/platform-debian
    - common/development
    - machines/remote
  server:
    - common/platform-debian
    - machines/server
