# Compilation installation path.
# Supports environment variable expansions using ${VARIBLE}
install_path: ${HOME}/.config

# The file suffix used for override files
override_suffix: override

# The file suffix to use for installation files
install_suffix: install

groups:
  - base
  - packages
  - arch/cli
  - arch/gui
  - arch/i3wm
  - arch/kde
  - arch/targets/xps
  - debian/cli
  - debian/targets/remote
  - debian/targets/xps

base_groups: [base]
profiles:
  arch:
    - arch/cli
  arch-i3wm:
    - arch/cli
    - arch/gui
    - arch/i3wm
  arch-kde:
    - arch/cli
    - arch/gui
    - arch/kde
  xps:
    - arch/cli
    - arch/gui
    - arch/i3wm
    - arch/targets/xps
  remote:
    - debian/cli
    - debian/targets/remote
