#!/usr/bin/env bash
source "$DOTS_SOURCE/base/bash/environment"
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
group=${DIR#$DOTS_SOURCE/}
echo -e "$YEL*** Installing group $PUR$group/$(basename $0 .install)$RST"

# Both source and target files should be set to 600 permissions. Git does not
# track permissiosn otherwise so this is a requirement.
chmod 600 "$DOTS_SOURCE/base/gnupg/gpg-agent.conf" "$XDG_CONFIG_HOME/gnupg/gpg-agent.conf"

mkdir -p "$HOME/.gnupg"
ln -sf "$XDG_CONFIG_HOME/gnupg/gpg-agent.conf" "$HOME/.gnupg/"