#!/usr/bin/bash

# Builtins-Base
alias cp="cp -i"     # overwrite confirmation
alias mv="mv -i"     # overwrite confirmation
alias df="df -h"     # human-readable sizes
alias du="du -h"     # human-readable sizes
alias free="free -h" # human-readable sizes
alias ll="ls -l"     # detailed file list
alias la="ls -lA"    # detailed file list with hidden files
alias wh="which -aS" # Informative version of which
alias less='less --RAW-CONTROL-CHARS'
alias sudo='sudo '   # Carry over environment & forces sudo to use aliases
alias vim="nvim"     # Force nvim usage
alias oldvim="\vim"  # Use dealiased vim

# Generic
alias ls="LC_COLLATE=C ls --group-directories-first --color=always --classify -h"

# Utils
## Repositories
alias ds="cd ${DOTS_SOURCE}"
alias rp="cd ${REPOSITORY_ROOT}"
alias rpa="cd ${REPOSITORY_ROOT}/aakashhemadri"
alias rpb="cd ${REPOSITORY_ROOT}/thebridge"
alias lk="cd ${REPOSITORY_ROOT}/linux"

## personal
alias rphome="cd ${REPOSITORY_ROOT}/aakashhemadri/aakashhemadri.github.io"
alias rpportfolio="cd ${REPOSITORY_ROOT}/aakashhemadri/portfolio"
alias rpblog="cd ${REPOSITORY_ROOT}/aakashhemadri/blog"
alias rpcertificates="cd ${REPOSITORY_ROOT}/aakashhemadri/certificates"
alias rpcourses="cd ${REPOSITORY_ROOT}/aakashhemadri/courses"
alias rptutorials="cd ${REPOSITORY_ROOT}/aakashhemadri/tutorials"

## linux
alias lkml="cd ${REPOSITORY_ROOT}/linux/linux-mainline"
alias lks="cd ${REPOSITORY_ROOT}/linux/linux-stable"
alias lkn="cd ${REPOSITORY_ROOT}/linux/linux-next"
alias lkds="cd drivers/staging"

# Applications
alias mutt="neomutt"
alias serve="python3 -m http.server"

## docker-compose
alias dc="docker-compose"
alias dcup="docker-compose up -d"
alias dcdown="docker-compose down"
alias dclog="docker-compose logs -f"

## git
alias gresign="git rebase --exec 'git commit --amend --no-edit -n -S' -i HEAD" # git resign all commits from history
