#!/usr/bin/bash

alias cp="cp -i"     # overwrite confirmation
alias mv="mv -i"     # overwrite confirmation
alias df="df -h"     # human-readable sizes
alias du="du -h"     # human-readable sizes
alias free="free -h" # human-readable sizes
alias ll="ls -l"     # detailed file list
alias la="ls -lA"    # detailed file list with hidden files
alias wh="which -aS" # Informative version of which
alias less='less --RAW-CONTROL-CHARS'
alias sudo='sudo '   # Carry over environment & forces sudo to use aliases
alias vim="nvim"     # Force nvim usage
alias oldvim="\vim"  # Use dealiased vim

# Better LS sorting
#  - Collate listings so dot files are listed first
#  - Colorize the list
#  - Classify files (such as executables with a *)
#  - always show sizes in human readable formats
alias ls="LC_COLLATE=C ls --group-directories-first --color=always --classify -h"

# Server the current directory over port 8000 using python
alias serve="python3 -m http.server"

# docker-compose
#
alias dc="docker-compose"
alias dcup="docker-compose up -d"
alias dcdown="docker-compose down"
alias dclog="docker-compose logs -f"

# git

alias gresign="git rebase --exec 'git commit --amend --no-edit -n -S' -i HEAD" # git resign all commits from history
