#!/usr/bin/bash
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo -e "$YEL*** Installing $PUR${DIR#$DOTS_SOURCE/}/$(basename $0 .install)$RST"

rm -f "$HOME/.xinitrc" \
    "$HOME/.Xresource" \
    "$HOME/.Xmodmap" \
    "$HOME/.xsession"

ln -sf $XDG_CONFIG_HOME/xorg/xinitrc $HOME/.xinitrc
ln -sf $XDG_CONFIG_HOME/xorg/Xresource $HOME/.Xresource
ln -sf $XDG_CONFIG_HOME/xorg/Xmodmap $HOME/.Xmodmap
ln -sf $XDG_CONFIG_HOME/xorg/xsession $HOME/.xsession

