#!/usr/bin/bash
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo -e "$YEL*** Installing $PUR${DIR#$DOTS_SOURCE/}/$(basename $0 .install)$RST"

# Both source and target files should be set to 600 permissions. Git does not
# track permissiosn otherwise so this is a requirement.
chmod 600 "$DOTS_SOURCE/linux/gnupg/gpg-agent.conf" "$XDG_CONFIG_HOME/gnupg/gpg-agent.conf"

mkdir -p "$HOME/.gnupg"
ln -sf "$XDG_CONFIG_HOME/gnupg/gpg-agent.conf" "$HOME/.gnupg/"