#!/usr/bin/env bash
source "$DOTS_SOURCE/base/bash/environment"
echo -e "$YEL*** common/platform-arch/yay"

if ! hash yay 2>/dev/null; then
  if [[ -d XDG_CACHE_HOME/yay/yay ]]; then
    rm -rf $XDG_CACHE_HOME/yay/yay
  fi
  echo -e "$GRE==>$TUR Installing yay."
  git clone https://aur.archlinux.org/yay.git $XDG_CACHE_HOME/yay/yay
  (cd $XDG_CACHE_HOME/yay/yay/ && makepkg -si --noconfirm)
else
  echo -e "$GRE==>$TUR yay is preinstalled!"
fi

