#!/usr/bin/env bash


source "$DOTS_SOURCE/base/bash/environment"

echo -e "${YEL}*** base/vim"
echo -e "${GRE}==>${TUR} Cleaning existing vim configs"
rm -f "$HOME/.vimrc" \
    "$HOME/.viminfo"

PLUG_SOURCE="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

if [[ ! -e $XDG_CONFIG_HOME/vim/autoload/plug.vim ]]; then
    echo -e "${GRE}==>${TUR} Installing vim-plug"
    curl --create-dirs -sSfLo $VIMCONFIG/autoload/plug.vim "$PLUG_SOURCE"
fi
