#!/usr/bin/env bash
source "$DOTS_SOURCE/base/bash/environment"
echo -e "$YEL*** base/ssh"
# Both source and target files should be set to 600 permissions. Git does not
# track permissiosn otherwise so this is a requirement.
echo -e "$GRE==>$TUR Setting ssh/config permission to 600"
chmod 600 "$DOTS_SOURCE/base/ssh/config" "$XDG_CONFIG_HOME/ssh/config"

echo -e "$GRE==>$TUR Linking ssh/config"
mkdir -p "$HOME/.ssh"
ln -sf "$XDG_CONFIG_HOME/ssh/config" "$HOME/.ssh/"
